### ISSUE TITLE
[BUG] Biomes o' Plenty planks cannot be crafted into chests

### ISSUE THREAD

**Issue by DanteTorn** [AMPZNetwork/Kingdoms-of-the-Valley#1]
**Describe the bug**
Biomes o' Plenty planks cannot be crafted into chests

**To Reproduce**
1. Acquire BoP wood
2. Craft into planks
3. Arrange in a circle in crafting grid
4. No chest appears in output slot

**Expected behavior**
From the fact that these are planks, I'd expect them to at least be able to be crafted into basic oak chests.
Ideally, you would be able to make the unique chests of Upgrade Aquatic using the equivalent planks (BoP willow planks -> UA willow chest).

**Crash Log**
N/A

**Screenshots**
![2022-02-18_22 48 38](https://user-images.githubusercontent.com/35230199/154772493-8e7b320f-34e5-4af6-bf02-5a6dc40ab234.png)

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - Kingdoms Of The Valley 1.6-B7
 - ATlauncher
 - Optifine

**Comment by LabsZero** [comment]
Thank you for your bug report, I shell look into a fix in the next update.
