### ISSUE TITLE
[BUG] Cannot enter Nether with NetherPortalFix enabled (1.7.1-B8)

### ISSUE THREAD

**Issue by Sir-Cyber** [AMPZNetwork/Kingdoms-of-the-Valley#2]
**Describe the bug**
Cannot use Nether Portals in survival or creative while NetherPortalFix model is enabled. 

**To Reproduce**

1.  Create world in any game state
2.  Create Nether Portal
3. Go through Nether Portal

**Expected behavior**
Player should be teleported to Nether

**Actual behavior**
User remains stuck on "Loading terrain..." during the transition. At least 15 mins was observed at this screen before a forced termination of the Java Platform SE binary was executed from task manager.

**Crash logs**
No crashes are experienced, thus no logs can be supplied. However, a log file from two different states have been provided.
2022-03-25-2.log.gz Should be a record of attempting to go to the nether with NetherPortalFix ENABLED
2022-03-25-3.log.gz Is an attempt to enter the Nether with NetherPortalFix DISABLED. Unfortunately in this particular save removing NetherPortalFix did not help.

**Screenshots**
Attached is a screen shot of my task manager read out during an attempt to enter the Nether.
[2022-03-25-3.log.gz](https://github.com/AMPZNetwork/Kingdoms-of-the-Valley/files/8354036/2022-03-25-3.log.gz)
[2022-03-25-2.log.gz](https://github.com/AMPZNetwork/Kingdoms-of-the-Valley/files/8354058/2022-03-25-2.log.gz)

**Basic Informations (please complete the following information):**
 - OS: [Windows 10]
 - Kingdoms Of The Valley [1.7.1-B8, 1.7.1-B7]
![KotV_nether_resource_load](https://user-images.githubusercontent.com/33306447/160208511-89a82216-baad-4ee3-9021-3b3794845d41.PNG)

 - Platform [ATLauncher]
 - Extra mods added by you [No additional Mods]
 - Disabled mods [NetherPortalFix_1.16.3-7.2.1]

**Comment by LabsZero** [comment]
Followed your step and the issue seems to not be present. Maybe the issue is due to you having two java programmes running.

**Comment by Sir-Cyber** [comment]
I will have a few friends test out the steps and see if it is unique to my computer.

**Comment by LabsZero** [comment]
Ok please update me on here what they come back with.

**Comment by Sir-Cyber** [comment]
I was only able to get one friend who isn't on my network to test this issue and they did NOT experience any problems.
It must be my end. The question now is why me?
