### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by renorien** [AMPZNetwork/Kingdoms-of-the-Valley#5]
**Describe the bug**
Tree Harvester - This mod is suppose to allow you to sneak and chop down a tree and it auto places a sapling down after word if you have one, however even if you do have the sapling it doesn't always place them only about 1 out of 5 times, on top of that the sneaking to cut the tree doesn't work all the time either, sometimes you cut just one log with a FULL health weapon. Repeating trying to cut the same tree will ONLY work sometimes as well. 

**To Reproduce**
1. Go to a tree
2. Click Shift and break the tree block on the bottom

**Expected behavior**
I expect what will happen is you will have a bunch of tree that do not cut down with the tree harvesting. And the sapling wont plant

**Crash Log**
NO crash log but  I was playing on a server provided by bisecthosting

**Screenshots**

**Basic Informations (please complete the following information):**
 - OS: Windows 11
 - Kingdoms Of The Valley 1.18.2
 - Platform Curseforge
 - Extra mods added by you Optifine

**Comment by LabsZero** [comment]
It's best to report this to the mod author to see if they can fix this issue. For now use the pack without Optifine if you can.
