### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AForgottenKing** [AMPZNetwork/Kingdoms-of-the-Valley#6]
**I keep getting an "error in currently selected data packs" error message even though I have none selected. I've tried loading it up with vanilla assists as the option pops up, but my game instantly crashes. It won't even let me load up my previous saved worlds.**

**To Reproduce**
1. Go to load game 
2. Click on "test world" (the name I give to all mod packs when trying them out)
3. after loading screen I get a blue screen and "error in currently selected data packs"

**Expected behavior**
Loading up my save after update to the mod pack

**Crash Log**
If the bug includes a crash, please paste or link it here.
(not sure how)
**Screenshots**
![image](https://user-images.githubusercontent.com/89614148/225980872-1aa762db-4b95-4044-9459-61d1bb70f7a7.png)

**Basic Information (please complete the following information):**
 - OS:  Windows 11
 - Kingdoms Of The Valley v 1.18.2
 - Platform  technicpack
 - Extra mods added by you none

**Comment by LabsZero** [comment]
Was the a direct update from the 1.16.5 version?

**Comment by AForgottenKing** [comment]
yes it was

**Comment by LabsZero** [comment]
Unfortunately there is nothing I can do to fix it. I’m afraid you world is not compatible with 2.0. You will have to create a new world or downgrade to 1.9

**Comment by AForgottenKing** [comment]
Thank you for all your help. It really means a lot that you looked into it.
I've started a new world and its working just fine now

**Comment by LabsZero** [comment]
Glad to hear it. Sorry that you had to but at least you now know you have all the new features this update brings.
